Repository adobecom/nala, pull requests merged in 2023-08, with the labels that each got.

#148 MWPW-134592 : Fixing daily run failures
  selectors/milo/howto.block.page.js
  tests/milo/faas.block.test.js
  tests/milo/georouting.feature.test.js
  tests/milo/htmlextn.feature.test.js
Labels: run-nala

#149 [ Daily Run] Carouse block script fix for Windows platform
  features/milo/carousel.block.spec.js
  selectors/milo/carousel.block.page.js
  tests/milo/carousel.block.test.js
Labels: run-nala, @carousel

#150 MWPW-134592 : Fixing daily run failures ( Columns-block )
  selectors/milo/columns.block.page.js
Labels: @columns, run-nala

#152 [MWPW-135370] Update browserParams to match new GeoRouting logic
  features/feds/a11y.spec.js
  features/feds/breadcrumbs.spec.js
  features/feds/consent.spec.js
  features/feds/footer.spec.js
  features/feds/header.spec.js
  features/feds/jarvis.spec.js
  features/feds/search.spec.js
  features/feds/userprofile.spec.js
  features/milo/aside.block.spec.js
Labels: trivial

#154 MWPW-135502: Update page object class from named entity class to default class
  .github/workflows/manual.yml
  selectors/milo/accordion.block.page.js
  selectors/milo/carousel.block.page.js
  selectors/milo/columns.block.page.js
  selectors/milo/georouting.feature.page.js
  selectors/milo/howto.block.page.js
  selectors/milo/icon.block.page.js
  selectors/milo/marquee.block.page.js
  selectors/milo/media.block.page.js
  selectors/milo/modal.block.page.js
  selectors/milo/quote.block.page.js
  selectors/milo/review.block.page.js
  selectors/milo/text.block.page.js
  selectors/milo/zpattern.block.page.js
  tests/milo/accordion.block.test.js
  tests/milo/carousel.block.test.js
  tests/milo/columns.block.test.js
  tests/milo/georouting.feature.test.js
  tests/milo/howto.block.test.js
  tests/milo/icon.block.test.js
  tests/milo/marquee.block.test.js
  tests/milo/media.block.test.js
  tests/milo/modal.block.test.js
  tests/milo/quote.block.test.js
  tests/milo/review.block.test.js
  tests/milo/text.block.test.js
  tests/milo/zpattern.block.test.js
Labels: run-nala

#155  MWPW-135564 : Upgrade Playwright to the latest version (1.37)
  package-lock.json
  package.json
Labels: run-nala
