Repository adobecom/nala, pull requests merged in 2023-11, with the labels that each got.

#198 commenting linux-webkit project
  playwright.config.js
  run.sh
Labels: run-nala

#196 CodeBlock and Draft
  configs/helpx.config.js
  envs/envs.js
  features/helpx/beforeAfter.spec.js
  features/helpx/codeBlock.spec.js
  features/helpx/draft.spec.js
  features/helpx/procedure.spec.js
  selectors/helpx/beforeafter.page.js
  selectors/helpx/beforeafter.selectors.js
  selectors/helpx/codeBlock.page.js
  selectors/helpx/draft.page.js
  selectors/helpx/procedure.page.js
  selectors/helpx/procedure.selectors.js
  tests/helpx/beforeafter.test.js
  tests/helpx/codeBlock.test.js
  tests/helpx/draft.test.js
  tests/helpx/procedure.test.js
Labels: run-on-helpx-live

#199 Add video test script to Modal feature test suite
  features/milo/modal.block.spec.js
  selectors/milo/modal.block.page.js
  tests/milo/marquee.block.test.js
  tests/milo/modal.block.test.js
Labels: run-nala, @modal

#201 [MWPW-138844] : Merch-card block tests scripts
  features/milo/merchcard.block.spec.js
  libs/slack.js
  selectors/milo/merchcard.block.page.js
  tests/milo/merchcard.block.test.js
  utils/reporters/base-reporter.js
Labels: run-nala

#202 [MWPW-139022] : Card block tests scripts
  features/milo/card.block.spec.js
  selectors/milo/card.block.page.js
  tests/milo/card.block.test.js
Labels: run-nala

#203 [MWPW-139085] : Chart block tests scripts
  features/milo/chart.block.spec.js
  selectors/milo/chart.block.page.js
  tests/milo/chart.block.test.js
Labels: run-nala

#205 [MWPW-139139] : Tabs block tests scripts
  features/milo/tabs.block.spec.js
  selectors/milo/tabs.block.page.js
  tests/milo/merchcard.block.test.js
  tests/milo/tab.block.test.js
Labels: run-nala

#206 [MWPW-139138] : Table block tests scripts
  features/milo/table.block.spec.js
  selectors/milo/table.block.page.js
  tests/milo/table.block.test.js
  utils/reporters/base-reporter.js
Labels: run-nala

#207 Run nala tests on stage env
  global.setup.js
Labels: run-nala

#208 [MWPW-139314] : Action-item Block tests scripts
  .github/workflows/daily.yml
  .github/workflows/debug.yml
  .github/workflows/manual.yml
  .github/workflows/self.yml
  features/milo/actionitem.block.spec.js
  global.setup.js
  selectors/milo/actionitem.block.page.js
  tests/milo/actionitem.block.test.js
  utils/reporters/base-reporter.js
Labels: run-nala

#212 Update Merch card test scripts as per the changes : MWPW-138882: Commerce v3 Merch Card
  selectors/milo/merchcard.block.page.js
  tests/milo/merchcard.block.test.js
Labels: run-nala

#215 [MWPW-139561] FEDS to Milo: Run FEDS tests for every Milo PR when label is added
  features/milo/breadcrumbs.block.spec.js
  features/milo/footer.block.spec.js
  features/milo/header.block.spec.js
  tests/milo/breadcrumbs.block.test.js
  tests/milo/footer.block.test.js
  tests/milo/header.block.test.js
Labels: run-nala
