Repository adobecom/nala, pull requests merged in 2023-02, with the labels that each got.

#55 DC converter test
  docs/Test.pdf
  envs/envs.js
  features/dc_converter.spec.js
  selectors/dc_converter.selectors.js
  tests/dc_converter.test.js
Labels: run-nala, @converter

#58 Updated github actions for upload-artifact
  .github/workflows/daily.yml
  .github/workflows/debug.yml
  .github/workflows/manual.yml
  .github/workflows/self.yml
Labels: run-nala, trivial

#60 updated README
  README.md
Labels: trivial

#65 Added carousel tests
  features/carousel.spec.js
  selectors/carousel.selectors.js
  tests/carousel.test.js
Labels: run-nala, @carousel

#66 fixed IMS login test bacom prod url
  features/imslogin.spec.js
  tests/carousel.test.js
Labels: run-nala, trivial

#61 Fix URL for DC PR testing
  features/dc_converter.spec.js
  features/parse.js
  tests/dc_converter.test.js
Labels: run-nala, @converter

#63 Test all L2 converter verbs
  docs/dc/Small_Excel.xlsx
  docs/dc/Small_JPG.jpg
  docs/dc/Small_PDF.pdf
  docs/dc/Small_PPT.pptx
  docs/dc/Small_Word.docx
  envs/envs.js
  features/dc_converter.spec.js
  selectors/dc_converter.selectors.js
  tests/dc_converter.test.js
Labels: run-nala, @converter

#67 Parse update for consumer PR testing
  envs/envs.js
  features/carousel.spec.js
  features/columns.spec.js
  features/faas.spec.js
  features/failedblock.spec.js
  features/howto.spec.js
  features/imslogin.spec.js
  features/marketo.spec.js
  features/marquee.spec.js
  features/modal.spec.js
  features/parse.js
Labels: run-nala

#68 Added stage url check
  utils/extract-test-title.js
Labels: run-nala

#71 Removed workaround for CSP issue
  features/parse.js
  tests/dc_converter.test.js
Labels: run-nala

#69 [MWPW-126307] Added first FEDS consent check
  .gitignore
  envs/envs.js
  features/consent.spec.js
  features/parse.js
  selectors/consent.selectors.js
  tests/consent.test.js
Labels: run-nala, @feds-consent

#57 Playwright version update and Dependencies update
  package-lock.json
  package.json
  tests/modal.test.js
Labels: run-nala
