Repository adobecom/nala, pull requests merged in 2023-03, with the labels that each got.

#64 HTML Extension Automation Test
  envs/envs.js
  features/faas.spec.js
  features/html_ext.spec.js
  features/imslogin.spec.js
  selectors/faas.selectors.js
  selectors/html_ext.selectors.js
  tests/faas.test.js
  tests/html_ext.test.js
Labels: run-nala, @html

#72 Review block smoke test
  features/dc/converter_L1.spec.js
  features/dc/converter_L2.spec.js
  features/review.spec.js
  selectors/review.selectors.js
  tests/review.test.js
Labels: run-nala, @review_block

#73 Cross Platform testing in GitHub CI
  .github/workflows/daily.yml
  .github/workflows/debug.yml
  .github/workflows/manual.yml
Labels: run-nala

#74 [MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames
  selectors/marquee.selectors.js
Labels: run-nala, trivial

#78 added staging environment for BACOM
  envs/envs.js
Labels: trivial

#76 MWPW-127667 Update playwright configuration
  .gitignore
  playwright.config.js
Labels: run-nala

#81 Addressing failures in Daily Runs
  features/failedblock.spec.js
  features/imslogin.spec.js
  tests/carousel.test.js
  tests/faas.test.js
  tests/imslogin.test.js
Labels: run-nala

#80 DC sign in tests
  tests/dc/converter_L1.test.js
  tests/dc/converter_L2.test.js
  tests/imslogin.test.js
  utils/imslogin.js
Labels: run-nala

#83 DC sign-in tests
  tests/dc/converter_L1.test.js
  tests/dc/converter_L2.test.js
  tests/imslogin.test.js
  utils/imslogin.js
Labels: run-nala

#85 [MWPW-128269] Update FEDS NALA envs
  envs/envs.js
Labels: run-nala, @feds-consent

#84 HTML extension test uses locale urls
  features/html_ext.spec.js
  tests/html_ext.test.js
Labels: run-nala, @html

#86 Workaround for webkit test failure with click()
  selectors/dc_converter.selectors.js
  tests/dc/converter_L1.test.js
  tests/dc/converter_L2.test.js
Labels: run-nala

#40 GeoRouting E2E Test
  features/milo/faas.spec.js
  features/milo/georouting.spec.js
  features/milo/georoutingV2.spec.js
  selectors/feds/consent.selectors.js
  selectors/milo/georouting.selectors.js
  selectors/milo/georoutingV2.selectors.js
  tests/milo/georouting.test.js
  tests/milo/georoutingV2.test.js
  tests/milo/html_ext.test.js
Labels: run-nala, @georouting, @georoutingV2

#93 Daily Run test fixes
  tests/milo/faas.test.js
  tests/milo/modal.test.js
Labels: run-nala, @modal, @html

#95 Updated playwright and dev dependencies
  package-lock.json
  package.json
Labels: run-nala

#79 [MWPW-126969] Added search component check & page-objects
  features/feds/search.spec.js
  pages/feds.consent.page.js
  pages/feds.footer.page.js
  pages/feds.header.page.js
  tests/feds/search.test.js
Labels: run-nala, @feds-search

#96 [MWPW-128064] Header/Footer component checks
  features/feds/footer.spec.js
  features/feds/header.spec.js
  pages/feds.header.page.js
  tests/feds/header.test.js
Labels: run-nala, @feds-header, @feds-footer
