Repository adobecom/nala, pull requests merged in 2024-06, with the labels that each got.

#363 Updating base reporter.
  configs/bacom-blog.config.js
  configs/bacom.config.js
  features/bacom/stats.spec.js
Labels: run-nala

#369 [Carousel] Update the carousel block wait time for the visibility check
  selectors/milo/carousel.block.page.js
  tests/milo/carousel.block.test.js
  tests/milo/video.block.test.js
Labels: run-nala

#359 Spec homepage - Elements updated as per the changes in Experience Cloud
  features/feds/homePageSanity.spec.js
  features/feds/locales/homePage.json
  selectors/feds/feds.homepagesanity.page.js
Labels: run-nala

#375 Revert "Revert "MWPW-147299""
  selectors/milo/howto.block.page.js
  tests/milo/howto.block.test.js
Labels: do not merge

#378 Fixing tab failures in github actions.
  tests/milo/tab.block.test.js
Labels: run-nala, @tabs

#380 Updating tag to bacomSmoke
  .github/workflows/bacom.daily.yml
Labels: run-nala

#384 Removed old form template test.
  features/milo/marketo.block.spec.js
  selectors/milo/marketo.block.page.js
  tests/milo/marketo.block.test.js
Labels: run-nala

#385 Fixing failing tab tests.
  tests/milo/tab.block.test.js
Labels: run-nala
